--Coursesec

INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 4 , 1 , 175 , 3  , 6 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 4 , 2 , 176 , 1  , 4 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 14 , 3 , 177 , 3  , 4 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 14 , 4 , 178 , 3  , 1 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 24 , 5 , 179 , 1  , 2 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 24 , 6 , 180 , 3  , 5 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 34 , 7 , 181 , 1  , 3 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 34 , 8 , 182 , 1  , 5 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 44 , 9 , 183 , 2  , 4 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 44 , 10 , 184 , 3  , 2 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 54 , 11 , 185 , 2  , 5 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 54 , 12 , 186 , 2  , 1 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 64 , 13 , 187 , 3  , 3 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 64 , 14 , 188 , 1  , 5 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 74 , 15 , 189 , 2  , 1 , 6 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 74 , 16 , 190 , 2  , 3 , 6 ) 


---REgs
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 22 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 23 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 24 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 25 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 26 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 27 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 28 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 29 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 30 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 31 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 32 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 33 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 34 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 35 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 36 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 37 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 38 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 39 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 40 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 41 , 52 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 42 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 43 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 44 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 45 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 46 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 47 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 48 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 49 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 50 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 51 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 52 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 53 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 54 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 55 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 56 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 57 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 58 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 59 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 60 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 61 , 54 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 62 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 63 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 64 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 65 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 66 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 67 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 68 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 69 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 70 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 71 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 72 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 73 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 74 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 75 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 76 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 77 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 78 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 79 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 80 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 81 , 56 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101 , 58 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 60 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 122 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 123 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 124 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 125 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 126 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 127 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 128 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 129 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 130 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 131 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 132 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 133 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 134 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 135 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 136 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 137 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 138 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 139 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 140 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 141 , 62 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 142 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 143 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 144 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 145 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 146 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 147 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 148 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 149 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 150 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 151 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 152 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 153 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 154 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 155 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 156 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 157 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 158 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 159 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 160 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 161 , 64 ) 
--cs
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 59 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 55 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 61 ) 


--as

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 55 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 61 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 63 ) 


--bios
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 51 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 57 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 61 ) 

--crimk

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 51 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 51) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 61 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 61 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 63 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 63 ) 

---his
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100 , 49 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101 , 49 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101 , 53 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101 , 59 ) 

---mat

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 64 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 64 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 53 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 53 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 57 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 57 ) 

--psy

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 53  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 53  ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 55  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 55  ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 57  ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 57  ) 

--busine
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 50 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 50 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 55 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 55 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 59 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 59 ) 



---grades


INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1921 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1922 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1923 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1924 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1925 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1926 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1927 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1928 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1929 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1930 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1931 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1932 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1933 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1934 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1935 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1936 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1937 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1938 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1939 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1940 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1941 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1942 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1943 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1944 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1945 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1946 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1947 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1948 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1949 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1950 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1951 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1952 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1953 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1954 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1955 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1956 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1957 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1958 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1959 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1960 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1961 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1962 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1963 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1964 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1965 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1966 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1967 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1968 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1969 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1970 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1971 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1972 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1973 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1974 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1975 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1976 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1977 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1978 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1979 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1980 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1981 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1982 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1983 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1984 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1985 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1986 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1987 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1988 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1989 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1990 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1991 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,1992 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,1993 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,1994 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1995 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,1996 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,1997 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,1998 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,1999 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2000 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2001 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2002 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2003 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2004 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2005 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2006 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2007 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2008 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2009 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2010 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2011 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2012 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2013 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2014 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2015 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2016 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2017 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2018 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2019 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2020 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2021 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2022 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2023 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2024 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2025 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2026 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2027 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2028 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2029 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2030 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2031 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2032 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2033 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2034 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2035 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2036 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2037 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2038 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2039 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2040 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2041 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2042 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2043 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2044 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2045 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2046 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2047 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2048 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2049 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2050 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2051 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2052 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2053 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2054 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2055 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2056 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2057 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2058 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2059 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2060 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2061 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2062 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2063 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2064 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2065 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2066 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2067 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2068 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2069 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2070 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2071 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2072 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2073 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2074 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2075 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2076 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2077 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2078 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2079 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2080 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2081 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2082 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2083 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2084 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2085 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2086 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2087 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2088 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2089 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2090 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2091 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2092 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2093 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2094 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2095 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2096 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2097 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2098 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2099 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2100 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2101 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2102 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2103 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2104 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2105 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2106 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2107 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2108 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2109 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2110 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2111 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2112 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2113 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2114 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2115 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2116 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2117 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2118 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2119 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2120 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2121 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2122 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2123 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2124 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2125 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2126 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2127 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2128 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2129 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2130 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2131 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2132 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2133 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2134 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2135 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2136 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2137 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2138 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2139 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2140 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2141 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2142 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2143 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2144 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2145 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2146 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2147 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2148 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2149 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2150 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2151 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2152 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2153 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2154 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2155 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2156 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2157 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2158 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2159 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2160 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2161 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2162 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2163 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2164 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2165 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2166 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2167 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2168 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2169 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2170 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2171 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2172 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2173 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2174 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2175 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2176 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2177 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2178 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2179 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2180 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2181 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2182 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2183 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2184 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2185 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2186 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2187 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2188 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2189 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2190 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2191 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2192 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2193 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2194 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2195 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2196 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2197 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2198 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2199 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2200 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2201 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2202 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2203 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2204 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2205 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2206 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2207 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2208 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2209 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2210 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2211 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2212 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2213 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2214 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2215 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2216 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2217 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2218 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2219 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2220 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2221 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2222 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2223 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2224 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2225 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2226 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2227 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2228 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2229 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2230 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2231 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2232 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2233 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2234 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2235 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2236 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2237 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2238 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2239 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2240 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2241 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2242 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2243 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2244 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2245 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2246 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2247 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2248 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2249 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2250 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2251 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2252 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2253 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2254 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2255 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2256 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2257 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2258 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2259 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2260 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2261 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2262 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2263 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2264 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2265 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2266 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2267 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2268 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2269 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2270 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2271 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2272 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2273 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2274 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2275 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2276 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2277 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2278 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2279 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2280 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2281 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2282 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2283 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2284 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2285 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2286 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2287 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2288 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2289 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2290 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2291 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2292 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2293 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2294 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2295 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2296 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2297 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2298 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2299 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2300 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2301 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2302 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2303 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2304 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2305 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2306 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2307 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2308 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2309 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2310 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2311 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2312 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2313 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2314 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2315 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2316 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2317 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2318 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2319 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2320 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2321 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2322 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2323 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2324 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2325 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2326 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2327 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2328 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2329 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2330 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2331 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2332 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2333 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2334 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2335 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2336 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2337 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2338 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2339 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2340 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2341 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2342 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2343 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2344 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2345 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2346 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2347 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2348 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2349 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2350 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2351 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2352 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2353 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2354 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2355 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2356 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2357 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2358 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2359 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2360 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2361 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2362 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2363 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2364 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2365 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2366 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2367 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2368 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2369 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2370 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2371 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2372 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2373 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2374 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2375 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2376 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2377 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2378 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2379 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2380 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2381 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2382 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2383 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2384 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2385 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2386 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2387 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2388 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2389 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2390 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2391 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2392 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2393 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2394 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2395 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2396 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2397 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2398 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2399 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2400 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2401 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2402 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2403 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2404 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2405 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2406 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2407 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2408 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2409 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2410 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2411 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2412 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2413 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2414 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2415 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2416 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2417 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2418 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2419 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2420 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2421 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2422 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2423 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2424 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2425 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2426 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2427 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2428 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2429 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2430 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2431 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2432 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2433 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2434 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2435 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2436 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2437 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2438 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2439 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2440 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2441 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2442 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2443 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2444 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2445 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2446 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2447 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2448 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2449 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2450 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2451 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2452 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2453 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2454 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2455 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2456 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2457 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2458 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2459 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2460 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2461 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2462 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2463 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2464 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2465 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2466 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2467 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2468 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2469 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2470 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2471 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2472 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2473 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2474 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2475 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2476 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2477 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2478 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2479 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2480 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2481 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2482 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2483 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2484 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2485 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2486 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2487 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2488 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2489 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2490 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2491 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2492 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2493 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2494 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2495 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2496 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2497 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2498 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2499 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2500 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2501 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2502 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2503 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2504 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2505 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2506 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2507 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2508 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2509 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2510 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2511 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2512 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2513 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2514 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2515 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2516 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2517 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2518 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2519 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2520 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2521 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2522 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2523 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2524 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2525 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2526 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2527 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2528 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2529 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2530 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2531 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2532 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2533 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2534 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2535 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2536 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2537 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2538 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2539 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2540 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2541 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2542 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2  ,2543 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2544 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2545 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2546 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2547 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2548 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2549 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5  ,2550 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2551 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2552 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2553 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2554 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3  ,2555 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7  ,2556 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4  ,2557 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6  ,2558 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2559 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1  ,2560 ) 

--