--Fall2018
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 5 , 1 , 180 , 3 , 6 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 5 , 2 , 181 , 1 , 4 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 15 , 3 , 182 , 3 , 4 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 15 , 4 , 183 , 3 , 1 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 25 , 5 , 184 , 1 , 2 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 25 , 6 , 185 , 3 , 5 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 35 , 7 , 186 , 1 , 3 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 35 , 8 , 187 , 1 , 5 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 45 , 9 , 188 , 2 , 4 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 45 , 10 , 189 , 3 , 2 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 55 , 11 , 190 , 2 , 5 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 55 , 12 , 191 , 2 , 1 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 65 , 13 , 192 , 3 , 3 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 65 , 14 , 193 , 1 , 5 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 75 , 15 , 194 , 2 , 1 , 5 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 75 , 16 , 195 , 2 , 3 , 5 ) 


--Reg
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 68 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 70 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 72 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101 , 74 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 76 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 78 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 80 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 80 ) 

--cs
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 75 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 77 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 79 ) 

--as
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41  ,71 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40  ,77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41  ,77 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41  ,79 ) 

--bs2018
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60  ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61  ,71 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60  ,75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61  ,75 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60  ,79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61  ,79 ) 

--cr
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 62 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 63 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 64 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 65 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 66 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 67 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 68 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 69 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 70 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 71 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 72 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 73 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 74 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 75 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 76 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 77 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 78 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 79 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 80 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 81 , 67 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 62 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 63 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 64 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 65 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 66 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 67 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 68 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 69 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 70 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 71 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 72 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 73 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 74 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 75 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 76 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 77 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 78 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 79 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 80 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 81 , 69 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 62 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 63 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 64 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 65 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 66 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 67 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 68 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 69 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 70 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 71 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 72 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 73 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 74 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 75 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 76 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 77 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 78 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 79 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 80 , 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 81 , 77 ) 

--his
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100, 75 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101, 75 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100, 77 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101, 77 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100, 79 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101, 79 ) 
--math
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 65 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 65 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 67 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 67 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 69 ) 

--psy
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 122 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 123 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 124 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 125 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 126 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 127 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 128 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 129 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 130 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 131 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 132 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 133 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 134 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 135 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 136 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 137 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 138 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 139 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 140 ,69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 141 ,69 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 122 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 123 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 124 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 125 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 126 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 127 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 128 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 129 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 130 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 131 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 132 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 133 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 134 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 135 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 136 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 137 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 138 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 139 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 140 ,71 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 141 ,71 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 122 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 123 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 124 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 125 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 126 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 127 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 128 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 129 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 130 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 131 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 132 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 133 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 134 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 135 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 136 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 137 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 138 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 139 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 140 ,73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 141 ,73 ) 

--bsuniess
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 66 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 66 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 69 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 69 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 73 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 73 ) 

--gtades
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2561 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2562 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2563 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2564 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2565 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2566 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2567 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2568 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2569 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2570 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2571 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2572 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2573 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2574 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2575 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2576 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2577 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2578 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2579 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2580 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2581 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2582 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2583 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2584 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2585 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2586 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2587 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2588 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2589 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2590 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2591 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2592 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2593 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2594 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2595 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2596 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2597 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2598 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2599 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2600 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2601 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2602 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2603 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2604 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2605 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2606 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2607 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2608 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2609 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2610 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2611 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2612 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2613 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2614 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2615 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2616 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2617 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2618 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2619 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2620 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2621 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2622 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2623 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2624 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2625 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2626 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2627 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2628 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2629 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2630 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2631 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2632 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2633 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2634 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2635 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2636 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2637 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2638 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2639 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2640 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2641 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2642 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2643 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2644 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2645 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2646 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2647 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2648 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2649 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2650 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2651 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2652 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2653 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2654 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2655 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2656 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2657 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2658 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2659 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2660 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2661 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2662 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2663 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2664 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2665 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2666 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2667 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2668 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2669 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2670 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2671 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2672 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2673 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2674 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2675 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2676 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2677 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2678 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2679 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2680 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2681 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2682 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2683 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2684 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2685 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2686 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2687 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2688 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2689 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2690 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2691 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2692 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2693 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2694 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2695 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2696 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2697 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2698 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2699 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2700 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2701 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2702 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2703 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2704 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2705 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2706 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2707 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2708 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2709 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2710 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2711 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2712 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2713 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2714 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2715 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2716 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2717 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2718 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2719 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2720 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2721 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2722 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2723 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2724 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2725 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2726 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2727 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2728 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2729 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2730 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2731 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2732 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2733 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2734 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2735 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2736 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2737 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2738 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2739 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2740 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2741 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2742 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2743 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2744 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2745 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2746 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2747 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2748 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2749 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2750 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2751 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2752 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2753 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2754 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2755 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2756 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2757 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2758 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2759 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2760 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2761 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2762 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2763 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2764 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2765 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2766 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2767 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2768 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2769 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2770 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2771 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2772 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2773 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2774 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2775 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2776 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2777 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2778 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2779 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2780 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2781 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2782 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2783 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2784 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2785 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2786 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2787 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2788 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2789 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2790 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2791 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2792 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2793 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2794 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2795 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2796 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2797 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2798 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2799 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2800 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2801 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2802 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2803 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2804 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2805 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2806 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2807 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2808 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2809 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2810 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2811 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2812 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2813 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2814 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2815 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2816 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2817 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2818 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2819 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2820 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2821 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2822 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2823 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2824 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2825 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2826 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2827 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2828 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2829 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2830 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2831 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2832 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2833 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2834 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2835 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2836 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2837 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2838 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2839 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2840 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2841 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2842 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2843 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2844 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2845 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2846 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2847 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2848 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2849 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2850 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2851 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2852 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2853 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2854 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2855 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2856 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2857 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2858 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2859 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2860 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2861 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2862 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2863 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2864 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2865 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2866 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2867 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2868 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2869 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2870 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2871 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2872 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2873 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2874 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2875 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2876 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2877 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2878 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2879 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2880 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2881 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2882 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2883 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2884 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2885 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2886 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2887 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2888 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2889 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2890 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2891 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2892 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2893 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2894 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2895 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2896 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2897 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2898 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2899 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2900 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2901 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2902 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2903 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2904 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2905 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2906 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2907 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2908 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2909 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2910 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2911 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2912 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2913 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2914 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2915 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2916 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2917 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2918 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2919 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2920 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2921 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2922 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2923 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2924 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2925 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2926 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2927 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2928 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2929 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2930 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2931 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2932 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2933 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2934 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2935 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2936 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2937 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2938 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2939 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2940 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2941 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2942 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2943 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2944 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2945 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2946 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2947 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2948 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2949 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2950 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2951 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2952 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2953 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2954 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2955 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2956 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2957 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2958 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2959 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2960 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2961 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2962 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2963 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2964 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2965 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2966 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2967 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2968 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2969 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2970 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2971 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2972 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2973 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2974 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2975 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2976 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2977 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2978 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2979 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2980 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2981 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2982 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2983 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2984 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2985 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2986 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2987 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2988 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 2989 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2990 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2991 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2992 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 2993 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 2994 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 2995 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2996 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 2997 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 2998 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 2999 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3000 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3001 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3002 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3003 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3004 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3005 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3006 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3007 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3008 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3009 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3010 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3011 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3012 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3013 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3014 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3015 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3016 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3017 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3018 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3019 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3020 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3021 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3022 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3023 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3024 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3025 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3026 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3027 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3028 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3029 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3030 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3031 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3032 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3033 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3034 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3035 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3036 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3037 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3038 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3039 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3040 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3041 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3042 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3043 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3044 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3045 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3046 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3047 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3048 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3049 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3050 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3051 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3052 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3053 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3054 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3055 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3056 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3057 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3058 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3059 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3060 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3061 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3062 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3063 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3064 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3065 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3066 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3067 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3068 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3069 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3070 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3071 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3072 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3073 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3074 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3075 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3076 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3077 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3078 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3079 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3080 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3081 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3082 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3083 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3084 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3085 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3086 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3087 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3088 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3089 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3090 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3091 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3092 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3093 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3094 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3095 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3096 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3097 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3098 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3099 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3100 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3101 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3102 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3103 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3104 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3105 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3106 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3107 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3108 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3109 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3110 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3111 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3112 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3113 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3114 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3115 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3116 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3117 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3118 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3119 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3120 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3121 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3122 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3123 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3124 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3125 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3126 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3127 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3128 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3129 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3130 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3131 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3132 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3133 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3134 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3135 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3136 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3137 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3138 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3139 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3140 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3141 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3142 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3143 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3144 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3145 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3146 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3147 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3148 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3149 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3150 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3151 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3152 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3153 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3154 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3155 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3156 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3157 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3158 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3159 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3160 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3161 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3162 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3163 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3164 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3165 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3166 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3167 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3168 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3169 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3170 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3171 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3172 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3173 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3174 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3175 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3176 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3177 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3178 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3179 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3180 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3181 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3182 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 2 , 3183 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3184 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3185 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3186 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3187 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3188 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3189 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 5 , 3190 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3191 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3192 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3193 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3194 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 3 , 3195 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 7 , 3196 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 4 , 3197 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 6 , 3198 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3199 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( 1 , 3200 ) 