--Spring2019coursesec
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 7 , 1  ,165  ,3 , 6  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 7 , 2  ,166 ,1 , 4  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 17 , 3  ,167  ,3 , 4  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 17 , 4  ,168  ,3 , 1  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 27 , 5  ,169  ,1 , 2  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 27 , 6  ,170  ,3 , 5  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 37 , 7  ,171  ,1 , 3  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 37 , 8  ,172  ,1 , 5  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 47 , 9  ,173 ,2 , 4  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 47 , 10  ,174 ,3 , 2  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 57 , 11  ,175  ,2 , 5  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 57 , 12  ,176  ,2 , 1  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 67 , 13  ,177  ,3 , 3  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 67 , 14  ,178  ,1 , 5  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 77 , 15  ,179  ,2 , 1  ,4 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 77 , 16  ,180  ,2 , 3  ,4 ) 


--reg

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 82 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 84 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 88 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 92 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 96 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 96 ) 

--CS

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21  ,83 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21  ,93 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20  ,95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21  ,95 ) 

--as

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 86 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 86 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 87 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 87 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 90 ) 

--bioscie

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 83 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 90 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 90 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 93 ) 

--criminolgy

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 83 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 89 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 89 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 94 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 94 ) 

--his*phi

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100  ,93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101  ,93 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100  ,83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101  ,83 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100  ,85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101  ,85 ) 


--math
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 95 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 93 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 93 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 85 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 85 ) 

--psy

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  , 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  , 83 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  , 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  , 91 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  , 95 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  , 95 ) 

--bnusienss

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (142, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (143, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (144, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (145, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (146, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (147, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (148, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (149, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (150, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (151, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (152, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (153, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (154, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (155, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (156, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (157, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (158, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (159, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (160, 83 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (161, 83 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (142, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (143, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (144, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (145, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (146, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (147, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (148, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (149, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (150, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (151, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (152, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (153, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (154, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (155, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (156, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (157, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (158, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (159, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (160, 81 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (161, 81 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (142, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (143, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (144, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (145, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (146, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (147, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (148, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (149, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (150, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (151, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (152, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (153, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (154, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (155, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (156, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (157, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (158, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (159, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (160, 91 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  (161, 91 ) 


--Grades

INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3201 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3202 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3203 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3204 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3205 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3206 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3207 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3208 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3209 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3210 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3211 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3212 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3213 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3214 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3215 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3216 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3217 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3218 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3219 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3220 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3221 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3222 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3223 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3224 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3225 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3226 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3227 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3228 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3229 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3230 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3231 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3232 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3233 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3234 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3235 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3236 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3237 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3238 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3239 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3240 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3241 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3242 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3243 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3244 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3245 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3246 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3247 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3248 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3249 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3250 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3251 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3252 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3253 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3254 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3255 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3256 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3257 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3258 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3259 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3260 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3261 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3262 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3263 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3264 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3265 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3266 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3267 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3268 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3269 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3270 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3271 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3272 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3273 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3274 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3275 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3276 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3277 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3278 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3279 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3280 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3281 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3282 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3283 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3284 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3285 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3286 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3287 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3288 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3289 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3290 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3291 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3292 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3293 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3294 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3295 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3296 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3297 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3298 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3299 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3300 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3301 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3302 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3303 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3304 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3305 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3306 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3307 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3308 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3309 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3310 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3311 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3312 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3313 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3314 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3315 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3316 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3317 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3318 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3319 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3320 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3321 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3322 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3323 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3324 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3325 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3326 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3327 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3328 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3329 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3330 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3331 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3332 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3333 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3334 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3335 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3336 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3337 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3338 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3339 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3340 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3341 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3342 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3343 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3344 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3345 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3346 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3347 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3348 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3349 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3350 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3351 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3352 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3353 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3354 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3355 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3356 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3357 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3358 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3359 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3360 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3361 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3362 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3363 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3364 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3365 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3366 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3367 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3368 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3369 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3370 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3371 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3372 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3373 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3374 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3375 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3376 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3377 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3378 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3379 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3380 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3381 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3382 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3383 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3384 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3385 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3386 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3387 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3388 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3389 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3390 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3391 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3392 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3393 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3394 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3395 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3396 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3397 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3398 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3399 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3400 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3401 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3402 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3403 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3404 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3405 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3406 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3407 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3408 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3409 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3410 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3411 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3412 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3413 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3414 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3415 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3416 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3417 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3418 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3419 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3420 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3421 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3422 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3423 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3424 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3425 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3426 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3427 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3428 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3429 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3430 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3431 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3432 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3433 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3434 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3435 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3436 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3437 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3438 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3439 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3440 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3441 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3442 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3443 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3444 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3445 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3446 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3447 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3448 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3449 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3450 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3451 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3452 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3453 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3454 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3455 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3456 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3457 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3458 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3459 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3460 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3461 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3462 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3463 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3464 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3465 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3466 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3467 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3468 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3469 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3470 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3471 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3472 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3473 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3474 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3475 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3476 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3477 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3478 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3479 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3480 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3481 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3482 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3483 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3484 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3485 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3486 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3487 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3488 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3489 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3490 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3491 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3492 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3493 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3494 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3495 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3496 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3497 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3498 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3499 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3500 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3501 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3502 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3503 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3504 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3505 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3506 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3507 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3508 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3509 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3510 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3511 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3512 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3513 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3514 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3515 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3516 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3517 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3518 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3519 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3520 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3521 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3522 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3523 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3524 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3525 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3526 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3527 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3528 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3529 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3530 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3531 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3532 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3533 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3534 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3535 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3536 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3537 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3538 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3539 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3540 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3541 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3542 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3543 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3544 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3545 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3546 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3547 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3548 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3549 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3550 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3551 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3552 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3553 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3554 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3555 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3556 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3557 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3558 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3559 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3560 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3561 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3562 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3563 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3564 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3565 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3566 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3567 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3568 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3569 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3570 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3571 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3572 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3573 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3574 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3575 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3576 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3577 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3578 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3579 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3580 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3581 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3582 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3583 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3584 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3585 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3586 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3587 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3588 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3589 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3590 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3591 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3592 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3593 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3594 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3595 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3596 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3597 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3598 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3599 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3600 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3601 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3602 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3603 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3604 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3605 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3606 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3607 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3608 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3609 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3610 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3611 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3612 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3613 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3614 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3615 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3616 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3617 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3618 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3619 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3620 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3621 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3622 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3623 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3624 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3625 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3626 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3627 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3628 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3629 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3630 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3631 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3632 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3633 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3634 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3635 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3636 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3637 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3638 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3639 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3640 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3641 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3642 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3643 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3644 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3645 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3646 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3647 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3648 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3649 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3650 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3651 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3652 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3653 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3654 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3655 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3656 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3657 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3658 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3659 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3660 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3661 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3662 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3663 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3664 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3665 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3666 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3667 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3668 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3669 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3670 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3671 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3672 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3673 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3674 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3675 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3676 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3677 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3678 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3679 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3680 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3681 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3682 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3683 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3684 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3685 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3686 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3687 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3688 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3689 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3690 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3691 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3692 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3693 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3694 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3695 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3696 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3697 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3698 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3699 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3700 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3701 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3702 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3703 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3704 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3705 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3706 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3707 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3708 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3709 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3710 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3711 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3712 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3713 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3714 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3715 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3716 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3717 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3718 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3719 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3720 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3721 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3722 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3723 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3724 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3725 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3726 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3727 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3728 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3729 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3730 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3731 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3732 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3733 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3734 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3735 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3736 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3737 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3738 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3739 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3740 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3741 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3742 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3743 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3744 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3745 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3746 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3747 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3748 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3749 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3750 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3751 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3752 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3753 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3754 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3755 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3756 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3757 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3758 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3759 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3760 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3761 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3762 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3763 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3764 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3765 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3766 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3767 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3768 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3769 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3770 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3771 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3772 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3773 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3774 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3775 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3776 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3777 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3778 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3779 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3780 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3781 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3782 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3783 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3784 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3785 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3786 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3787 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3788 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3789 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3790 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3791 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3792 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3793 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3794 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3795 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3796 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3797 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3798 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3799 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3800 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3801 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3802 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3803 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3804 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3805 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3806 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3807 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3808 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3809 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3810 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3811 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3812 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3813 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3814 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3815 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3816 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3817 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3818 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3819 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3820 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3821 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3822 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3823 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3824 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3825 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3826 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3827 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3828 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3829 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3830 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3831 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3832 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3833 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3834 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3835 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3836 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3837 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3838 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3839 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3840 ) 


