--Fall2019
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 8 , 1 , 169 , 3 , 6  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 8 , 2 , 170 , 1 , 4  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 18 , 3 , 171 , 3 , 4  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 18 , 4 , 172 , 3 , 1  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 28 , 5 , 173 , 1 , 2  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 28 , 6 , 174 , 3 , 5  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 38 , 7 , 175 , 1 , 3  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 38 , 8 , 176 , 1 , 5  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 48 , 9 , 177 , 2 , 4  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 48 , 10 , 178 , 3 , 2  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 58 , 11 , 179 , 2 , 5  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 58 , 12 , 180 , 2 , 1  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 68 , 13 , 181 , 3 , 3  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 68 , 14 , 182 , 1 , 5  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 78 , 15 , 183 , 2 , 1  ,3 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES  ( 78 , 16 , 184 , 2 , 3  ,3 ) 

--Regis
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 98 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 22 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 23 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 24 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 25 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 26 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 27 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 28 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 29 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 30 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 31 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 32 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 33 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 34 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 35 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 36 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 37 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 38 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 39 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 40 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 41 , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 42 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 43 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 44 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 45 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 46 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 47 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 48 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 49 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 50 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 51 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 52 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 53 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 54 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 55 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 56 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 57 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 58 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 59 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 60 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 61 , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 62 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 63 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 64 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 65 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 66 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 67 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 68 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 69 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 70 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 71 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 72 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 73 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 74 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 75 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 76 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 77 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 78 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 79 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 80 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 81 , 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 82 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 83 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 84 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 85 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 86 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 87 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 88 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 89 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 90 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 91 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 92 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 93 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 94 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 95 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 96 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 97 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 98 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 99 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 100 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 101 , 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 108 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 122 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 123 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 124 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 125 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 126 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 127 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 128 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 129 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 130 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 131 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 132 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 133 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 134 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 135 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 136 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 137 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 138 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 139 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 140 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 141 , 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 142 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 143 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 144 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 145 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 146 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 147 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 148 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 149 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 150 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 151 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 152 , 112 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 153 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 154 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 155 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 156 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 157 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 158 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 159 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 160 , 112) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 161 , 112 ) 

--cs
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 99 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 111 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21 , 101 ) 


--as
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 103 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 103 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 107 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 109 ) 
--biosc

INSERT INTO [BryantDB].[dbo].[Registration] VALUES (42, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (43, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (44, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (45, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (46, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (47, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (48, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (49, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (50, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (51, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (52, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (53, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (54, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (55, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (56, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (57, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (58, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (59, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (60, 110 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (61, 110 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES (42, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (43, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (44, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (45, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (46, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (47, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (48, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (49, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (50, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (51, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (52, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (53, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (54, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (55, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (56, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (57, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (58, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (59, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (60, 104 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (61, 104 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES (42, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (43, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (44, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (45, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (46, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (47, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (48, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (49, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (50, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (51, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (52, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (53, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (54, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (55, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (56, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (57, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (58, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (59, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (60, 106 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES (61, 106 ) 

--crimi
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 105 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 105 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 107 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81 , 111 ) 

--his&phi
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100   ,99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101   ,99 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100   ,101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101   ,101 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100   ,111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101   ,111 ) 

--mat
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 99 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 109 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 109 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 111 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 111 ) 

---psych
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  , 97 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  ,97  ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  , 100 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  , 100 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  , 102 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  , 102 ) 

--buiness
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 99 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 99 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 101 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 101 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 107 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 107 ) 


---gardes

INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3841 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3842 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3843 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3844 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3845 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3846 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3847 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3848 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3849 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3850 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3851 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3852 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3853 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3854 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3855 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3856 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3857 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3858 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3859 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3860 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3861 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3862 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3863 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3864 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3865 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3866 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3867 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3868 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3869 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3870 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3871 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3872 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3873 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3874 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3875 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3876 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3877 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3878 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3879 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3880 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3881 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3882 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3883 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3884 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3885 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3886 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3887 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3888 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3889 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3890 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3891 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3892 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3893 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3894 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3895 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3896 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3897 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3898 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3899 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3900 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3901 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3902 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3903 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3904 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3905 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3906 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3907 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3908 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3909 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3910 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3911 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3912 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3913 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3914 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3915 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3916 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3917 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3918 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3919 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3920 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3921 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3922 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3923 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3924 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3925 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3926 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3927 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3928 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3929 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3930 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3931 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3932 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3933 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3934 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3935 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3936 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3937 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3938 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3939 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3940 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3941 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3942 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3943 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3944 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3945 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3946 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3947 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3948 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3949 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3950 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3951 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3952 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3953 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3954 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3955 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3956 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3957 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3958 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3959 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3960 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3961 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3962 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3963 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3964 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3965 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3966 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3967 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3968 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3969 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3970 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3971 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3972 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3973 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3974 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3975 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3976 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3977 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3978 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3979 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3980 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3981 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3982 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3983 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3984 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3985 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3986 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 3987 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3988 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 3989 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 3990 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 3991 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3992 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3993 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3994 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3995 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3996 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 3997 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 3998 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 3999 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4000 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4001 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4002 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4003 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4004 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4005 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4006 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4007 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4008 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4009 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4010 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4011 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4012 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4013 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4014 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4015 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4016 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4017 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4018 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4019 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4020 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4021 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4022 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4023 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4024 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4025 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4026 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4027 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4028 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4029 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4030 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4031 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4032 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4033 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4034 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4035 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4036 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4037 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4038 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4039 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4040 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4041 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4042 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4043 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4044 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4045 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4046 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4047 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4048 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4049 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4050 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4051 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4052 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4053 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4054 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4055 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4056 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4057 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4058 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4059 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4060 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4061 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4062 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4063 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4064 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4065 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4066 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4067 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4068 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4069 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4070 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4071 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4072 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4073 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4074 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4075 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4076 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4077 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4078 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4079 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4080 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4081 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4082 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4083 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4084 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4085 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4086 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4087 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4088 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4089 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4090 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4091 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4092 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4093 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4094 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4095 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4096 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4097 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4098 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4099 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4100 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4101 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4102 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4103 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4104 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4105 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4106 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4107 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4108 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4109 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4110 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4111 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4112 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4113 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4114 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4115 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4116 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4117 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4118 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4119 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4120 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4121 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4122 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4123 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4124 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4125 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4126 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4127 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4128 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4129 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4130 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4131 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4132 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4133 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4134 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4135 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4136 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4137 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4138 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4139 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4140 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4141 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4142 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4143 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4144 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4145 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4146 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4147 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4148 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4149 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4150 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4151 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4152 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4153 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4154 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4155 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4156 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4157 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4158 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4159 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4160 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4161 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4162 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4163 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4164 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4165 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4166 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4167 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4168 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4169 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4170 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4171 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4172 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4173 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4174 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4175 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4176 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4177 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4178 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4179 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4180 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4181 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4182 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4183 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4184 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4185 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4186 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4187 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4188 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4189 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4190 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4191 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4192 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4193 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4194 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4195 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4196 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4197 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4198 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4199 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4200 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4201 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4202 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4203 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4204 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4205 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4206 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4207 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4208 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4209 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4210 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4211 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4212 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4213 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4214 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4215 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4216 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4217 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4218 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4219 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4220 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4221 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4222 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4223 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4224 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4225 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4226 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4227 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4228 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4229 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4230 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4231 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4232 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4233 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4234 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4235 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4236 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4237 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4238 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4239 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4240 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4241 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4242 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4243 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4244 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4245 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4246 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4247 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4248 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4249 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4250 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4251 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4252 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4253 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4254 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4255 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4256 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4257 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4258 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4259 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4260 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4261 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4262 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4263 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4264 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4265 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4266 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4267 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4268 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4269 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4270 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4271 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4272 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4273 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4274 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4275 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4276 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4277 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4278 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4279 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4280 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4281 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4282 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4283 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4284 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4285 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4286 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4287 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4288 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4289 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4290 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4291 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4292 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4293 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4294 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4295 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4296 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4297 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4298 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4299 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4300 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4301 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4302 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4303 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4304 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4305 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4306 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4307 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4308 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4309 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4310 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4311 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4312 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4313 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4314 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4315 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4316 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4317 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4318 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4319 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4320 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4321 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4322 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4323 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4324 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4325 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4326 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4327 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4328 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4329 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4330 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4331 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4332 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4333 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4334 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4335 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4336 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4337 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4338 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4339 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4340 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4341 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4342 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4343 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4344 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4345 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4346 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4347 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4348 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4349 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4350 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4351 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4352 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4353 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4354 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4355 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4356 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4357 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4358 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4359 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4360 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4361 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4362 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4363 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4364 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4365 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4366 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4367 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4368 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4369 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4370 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4371 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4372 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4373 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4374 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4375 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4376 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4377 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4378 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4379 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4380 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4381 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4382 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4383 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4384 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4385 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4386 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4387 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4388 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4389 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4390 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4391 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4392 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4393 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4394 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4395 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4396 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4397 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4398 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4399 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4400 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4401 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4402 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4403 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4404 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4405 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4406 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4407 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4408 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4409 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4410 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4411 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4412 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4413 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4414 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4415 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4416 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4417 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4418 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4419 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4420 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4421 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4422 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4423 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4424 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4425 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4426 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4427 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4428 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4429 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4430 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4431 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4432 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4433 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4434 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4435 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4436 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4437 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4438 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4439 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4440 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4441 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4442 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4443 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4444 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4445 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4446 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4447 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4448 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4449 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4450 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4451 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4452 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4453 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4454 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4455 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4456 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4457 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4458 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4459 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4460 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4461 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4462 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4463 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4464 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 6 , 4465 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4466 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4467 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 1 , 4468 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4469 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4470 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4471 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 5 , 4472 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4473 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4474 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4475 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4476 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 7 , 4477 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 4 , 4478 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 2 , 4479 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES  ( 3 , 4480 ) 
