--Spring2020
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (9  , 1  , 165 , 3 , 6  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (9  , 2  , 166 , 1 , 4  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (19  , 3  , 167 , 3 , 4  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (19  , 4  , 168 , 3 , 1  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (29  , 5  , 169 , 1 , 2  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (29  , 6  , 170 , 3 , 5  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (39  , 7  , 171 , 1 , 3  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (39  , 8  , 172 , 1 , 5  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (49  , 9  , 173 , 2 , 4  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (49  , 10  , 174 , 3 , 2  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (59  , 11  , 175 , 2 , 5  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (59  , 12  , 176 , 2 , 1  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (69  , 13  , 177 , 3 , 3  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (69  , 14  , 178 , 1 , 5  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (79  , 15  , 179 , 2 , 1  ,2 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES (79  , 16  , 180 , 2 , 3  ,2 ) 

---Registrstions

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11  ,113 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21  ,114 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41  ,116 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51  ,117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61  ,118 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101  ,122 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111  ,123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121  ,124 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  ,125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160  ,128 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161  ,128 ) 


--CS
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 121 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 123 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 125 ) 


--AMERIC
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 117 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 125 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41 , 127 ) 

--BIOSCIE
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 42 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 43 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 44 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 45 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 46 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 47 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 48 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 49 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 50 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 51 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 52 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 53 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 54 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 55 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 56 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 57 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 58 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 59 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 60 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 61 , 115 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 42 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 43 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 44 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 45 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 46 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 47 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 48 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 49 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 50 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 51 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 52 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 53 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 54 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 55 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 56 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 57 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 58 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 59 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 60 , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 61 , 125 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 42 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 43 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 44 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 45 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 46 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 47 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 48 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 49 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 50 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 51 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 52 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 53 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 54 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 55 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 56 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 57 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 58 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 59 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 60 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 61 , 127 ) 

--CRIMI
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,115 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,121 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,126 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,126 ) 

--HIS&OHI
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100  , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101  , 117 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100  , 119 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101  , 119 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100  ,127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101  ,127 ) 

--MATHE
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 115 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 120 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 120 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 102 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 103 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 104 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 105 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 106 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 107 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 108 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 109 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 110 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 111 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 112 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 113 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 114 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 115 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 116 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 117 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 118 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 119 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 120 , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 121 , 121 ) 

--PSHUCY
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 115 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 115 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 127 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 127 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 117 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 117 ) 

--BUSINESS
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160  , 121 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161  , 121 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160  , 123 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161  , 123 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160  , 125 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161  , 125 ) 



--Grades
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4481  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4482  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4483  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4484  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4485  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4486  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4487  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4488  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4489  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4490  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4491  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4492  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4493  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4494  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4495  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4496  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4497  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4498  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4499  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4500  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4501  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4502  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4503  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4504  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4505  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4506  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4507  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4508  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4509  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4510  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4511  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4512  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4513  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4514  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4515  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4516  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4517  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4518  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4519  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4520  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4521  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4522  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4523  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4524  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4525  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4526  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4527  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4528  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4529  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4530  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4531  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4532  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4533  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4534  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4535  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4536  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4537  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4538  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4539  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4540  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4541  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4542  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4543  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4544  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4545  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4546  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4547  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4548  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4549  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4550  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4551  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4552  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4553  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4554  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4555  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4556  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4557  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4558  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4559  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4560  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4561  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4562  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4563  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4564  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4565  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4566  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4567  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4568  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4569  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4570  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4571  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4572  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4573  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4574  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4575  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4576  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4577  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4578  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4579  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4580  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4581  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4582  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4583  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4584  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4585  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4586  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4587  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4588  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4589  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4590  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4591  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4592  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4593  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4594  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4595  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4596  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4597  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4598  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4599  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4600  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4601  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4602  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4603  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4604  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4605  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4606  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4607  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4608  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4609  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4610  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4611  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4612  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4613  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4614  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4615  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4616  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4617  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4618  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4619  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4620  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4621  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4622  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4623  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4624  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4625  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4626  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4627  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4628  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4629  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4630  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4631  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4632  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4633  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4634  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4635  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4636  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4637  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4638  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4639  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4640  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4641  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4642  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4643  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4644  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4645  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4646  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4647  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4648  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4649  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4650  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4651  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4652  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4653  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4654  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4655  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4656  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4657  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4658  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4659  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4660  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4661  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4662  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4663  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4664  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4665  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4666  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4667  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4668  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4669  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4670  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4671  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4672  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4673  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4674  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4675  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4676  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4677  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4678  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4679  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4680  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4681  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4682  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4683  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4684  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4685  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4686  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4687  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4688  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4689  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4690  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4691  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4692  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4693  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4694  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4695  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4696  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4697  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4698  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4699  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4700  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4701  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4702  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4703  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4704  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4705  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4706  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4707  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4708  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4709  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4710  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4711  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4712  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4713  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4714  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4715  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4716  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4717  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4718  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4719  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4720  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4721  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4722  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4723  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4724  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4725  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4726  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4727  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4728  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4729  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4730  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4731  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4732  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4733  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4734  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4735  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4736  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4737  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4738  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4739  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4740  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4741  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4742  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4743  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4744  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4745  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4746  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4747  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4748  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4749  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4750  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4751  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4752  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4753  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4754  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4755  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4756  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4757  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4758  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4759  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4760  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4761  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4762  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4763  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4764  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4765  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4766  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4767  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4768  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4769  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4770  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4771  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4772  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4773  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4774  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4775  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4776  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4777  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4778  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4779  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4780  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4781  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4782  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4783  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4784  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4785  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4786  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4787  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4788  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4789  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4790  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4791  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4792  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4793  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4794  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4795  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4796  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4797  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4798  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4799  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4800  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4801  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4802  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4803  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4804  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4805  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4806  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4807  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4808  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4809  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4810  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4811  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4812  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4813  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4814  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4815  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4816  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4817  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4818  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4819  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4820  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4821  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4822  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4823  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4824  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4825  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4826  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4827  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4828  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4829  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4830  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4831  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4832  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4833  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4834  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4835  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4836  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4837  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4838  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4839  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4840  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4841  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4842  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4843  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4844  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4845  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4846  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4847  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4848  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4849  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4850  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4851  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4852  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4853  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4854  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4855  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4856  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4857  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4858  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4859  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4860  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4861  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4862  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4863  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4864  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4865  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4866  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4867  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4868  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4869  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4870  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4871  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4872  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4873  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4874  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4875  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4876  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4877  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4878  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4879  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4880  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4881  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4882  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4883  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4884  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4885  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4886  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4887  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4888  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4889  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4890  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4891  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4892  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4893  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4894  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4895  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4896  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4897  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4898  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4899  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4900  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4901  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4902  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4903  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4904  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4905  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4906  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4907  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4908  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4909  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4910  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4911  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4912  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4913  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4914  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4915  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4916  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4917  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4918  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4919  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4920  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4921  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4922  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4923  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4924  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4925  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4926  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4927  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4928  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4929  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4930  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4931  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4932  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4933  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4934  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4935  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4936  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4937  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4938  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4939  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4940  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4941  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4942  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4943  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4944  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4945  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4946  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4947  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4948  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4949  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4950  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4951  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4952  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4953  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4954  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4955  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4956  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4957  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4958  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4959  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4960  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4961  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4962  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4963  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4964  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4965  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4966  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4967  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4968  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4969  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4970  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4971  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4972  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4973  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4974  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4975  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4976  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4977  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4978  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4979  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4980  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4981  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4982  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4983  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4984  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4985  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4986  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4987  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4988  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4989  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4990  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4991  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4992  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4993  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4994  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4995  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4996  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4997  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4998  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 4999  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5000  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5001  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5002  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5003  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5004  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5005  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5006  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5007  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5008  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5009  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5010  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5011  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5012  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5013  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5014  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5015  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5016  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5017  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5018  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5019  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5020  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5021  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5022  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5023  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5024  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5025  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5026  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5027  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5028  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5029  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5030  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5031  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5032  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5033  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5034  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5035  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5036  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5037  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5038  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5039  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5040  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5041  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5042  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5043  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5044  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5045  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5046  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5047  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5048  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5049  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5050  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5051  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5052  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5053  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5054  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5055  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5056  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5057  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5058  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5059  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5060  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5061  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5062  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5063  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5064  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5065  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5066  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5067  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5068  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5069  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5070  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5071  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5072  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5073  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5074  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5075  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5076  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5077  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5078  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5079  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5080  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5081  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5082  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5083  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5084  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5085  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5086  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5087  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5088  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5089  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5090  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5091  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5092  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5093  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5094  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5095  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5096  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5097  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5098  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5099  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5100  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5101  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5102  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5103  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5104  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5105  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5106  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5107  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5108  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5109  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5110  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5111  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5112  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5113  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5114  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5115  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5116  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5117  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5118  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5119  ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL , 5120  ) 