---fALL2020
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 10 , 1 , 170  , 3 , 6 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 10 , 2 , 171  , 1 , 4 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 20 , 3 , 172  , 3 , 4 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 20 , 4 , 173  , 3 , 1 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 30 , 5 , 174  , 1 , 2 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 30 , 6 , 175  , 3 , 5 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 40 , 7 , 176  , 1 , 3 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 40 , 8 , 177  , 1 , 5 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 50 , 9 , 178  , 2 , 4 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 50 , 10 , 179  , 3 , 2 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 60 , 11 , 180  , 2 , 5 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 60 , 12 , 181  , 2 , 1 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 70 , 13 , 182  , 3 , 3 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 70 , 14 , 183  , 1 , 5 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 80 , 15 , 184  , 2 , 1 , 1 ) 
INSERT INTO [BryantDB].[dbo].[CourseSection] VALUES ( 80 , 16 , 185  , 2 , 3 , 1 ) 

--REGIS
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 2  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 3  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 4  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 5  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 6  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 7  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 8  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 9  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 10  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 11  ,129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 12  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 13  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 14  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 15  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 16  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 17  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 18  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 19  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 20  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 21  ,130 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 22  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 23  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 24  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 25  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 26  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 27  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 28  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 29  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 30  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 31  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 32  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 33  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 34  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 35  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 36  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 37  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 38  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 39  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 40  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 41  ,132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51  ,133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61  ,134 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,136 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91  ,137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101  ,138 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111  ,139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121  ,140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141  ,142 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160  ,144 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161  ,144 ) 

---CS
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 131 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 141 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 2 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 3 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 4 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 5 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 6 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 7 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 8 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 9 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 10 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 11 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 12 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 13 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 14 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 15 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 16 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 17 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 18 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 19 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 20 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 21 , 143 ) 
--AS
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 22 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 23 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 24 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 25 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 26 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 27 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 28 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 29 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 30 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 31 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 32 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 33 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 34 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 35 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 36 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 37 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 38 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 39 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 40 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 41 , 133 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 22 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 23 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 24 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 25 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 26 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 27 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 28 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 29 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 30 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 31 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 32 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 33 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 34 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 35 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 36 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 37 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 38 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 39 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 40 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 41 , 135 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 22 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 23 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 24 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 25 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 26 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 27 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 28 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 29 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 30 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 31 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 32 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 33 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 34 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 35 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 36 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 37 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 38 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 39 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 40 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES  ( 41 , 137 ) 

--bio
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 131 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 141 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 42 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 43 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 44 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 45 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 46 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 47 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 48 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 49 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 50 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 51 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 52 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 53 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 54 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 55 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 56 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 57 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 58 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 59 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 60 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 61 , 143 ) 

--crimi
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,131 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,141 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 62  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 63  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 64  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 65  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 66  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 67  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 68  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 69  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 70  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 71  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 72  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 73  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 74  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 75  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 76  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 77  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 78  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 79  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 80  ,143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 81  ,143 ) 

--his
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101 , 137 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100 , 139 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101 , 139 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 82 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 83 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 84 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 85 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 86 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 87 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 88 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 89 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 90 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 91 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 92 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 93 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 94 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 95 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 96 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 97 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 98 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 99 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 100 , 141 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 101 , 141 ) 
--mat

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 131 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 135 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 143 ) 

--mat

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 131 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 131 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 135 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 102 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 103 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 104 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 105 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 106 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 107 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 108 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 109 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 110 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 111 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 112 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 113 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 114 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 115 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 116 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 117 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 118 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 119 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 120 , 143 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 121 , 143 ) 

--psy

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 129 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 129 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 132 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 132 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 122 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 123 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 124 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 125 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 126 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 127 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 128 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 129 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 130 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 131 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 132 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 133 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 134 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 135 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 136 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 137 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 138 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 139 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 140 , 137 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 141 , 137 ) 

--business
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 133 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 133 ) 

INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 135 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 135 ) 


INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 142 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 143 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 144 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 145 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 146 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 147 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 148 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 149 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 150 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 151 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 152 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 153 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 154 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 155 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 156 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 157 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 158 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 159 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 160 , 140 ) 
INSERT INTO [BryantDB].[dbo].[Registration] VALUES ( 161 , 140 ) 


--grades

INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5121 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5122 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5123 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5124 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5125 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5126 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5127 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5128 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5129 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5130 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5131 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5132 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5133 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5134 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5135 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5136 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5137 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5138 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5139 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5140 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5141 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5142 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5143 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5144 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5145 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5146 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5147 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5148 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5149 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5150 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5151 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5152 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5153 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5154 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5155 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5156 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5157 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5158 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5159 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5160 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5161 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5162 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5163 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5164 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5165 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5166 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5167 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5168 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5169 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5170 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5171 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5172 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5173 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5174 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5175 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5176 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5177 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5178 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5179 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5180 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5181 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5182 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5183 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5184 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5185 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5186 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5187 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5188 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5189 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5190 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5191 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5192 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5193 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5194 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5195 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5196 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5197 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5198 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5199 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5200 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5201 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5202 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5203 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5204 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5205 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5206 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5207 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5208 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5209 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5210 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5211 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5212 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5213 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5214 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5215 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5216 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5217 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5218 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5219 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5220 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5221 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5222 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5223 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5224 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5225 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5226 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5227 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5228 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5229 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5230 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5231 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5232 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5233 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5234 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5235 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5236 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5237 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5238 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5239 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5240 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5241 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5242 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5243 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5244 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5245 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5246 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5247 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5248 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5249 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5250 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5251 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5252 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5253 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5254 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5255 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5256 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5257 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5258 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5259 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5260 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5261 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5262 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5263 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5264 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5265 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5266 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5267 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5268 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5269 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5270 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5271 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5272 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5273 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5274 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5275 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5276 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5277 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5278 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5279 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5280 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5281 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5282 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5283 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5284 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5285 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5286 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5287 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5288 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5289 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5290 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5291 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5292 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5293 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5294 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5295 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5296 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5297 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5298 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5299 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5300 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5301 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5302 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5303 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5304 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5305 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5306 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5307 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5308 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5309 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5310 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5311 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5312 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5313 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5314 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5315 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5316 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5317 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5318 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5319 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5320 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5321 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5322 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5323 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5324 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5325 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5326 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5327 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5328 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5329 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5330 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5331 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5332 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5333 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5334 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5335 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5336 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5337 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5338 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5339 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5340 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5341 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5342 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5343 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5344 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5345 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5346 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5347 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5348 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5349 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5350 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5351 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5352 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5353 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5354 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5355 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5356 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5357 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5358 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5359 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5360 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5361 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5362 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5363 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5364 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5365 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5366 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5367 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5368 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5369 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5370 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5371 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5372 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5373 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5374 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5375 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5376 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5377 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5378 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5379 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5380 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5381 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5382 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5383 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5384 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5385 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5386 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5387 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5388 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5389 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5390 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5391 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5392 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5393 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5394 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5395 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5396 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5397 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5398 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5399 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5400 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5401 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5402 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5403 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5404 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5405 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5406 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5407 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5408 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5409 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5410 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5411 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5412 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5413 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5414 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5415 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5416 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5417 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5418 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5419 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5420 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5421 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5422 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5423 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5424 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5425 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5426 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5427 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5428 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5429 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5430 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5431 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5432 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5433 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5434 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5435 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5436 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5437 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5438 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5439 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5440 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5441 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5442 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5443 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5444 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5445 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5446 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5447 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5448 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5449 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5450 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5451 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5452 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5453 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5454 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5455 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5456 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5457 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5458 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5459 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5460 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5461 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5462 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5463 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5464 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5465 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5466 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5467 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5468 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5469 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5470 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5471 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5472 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5473 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5474 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5475 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5476 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5477 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5478 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5479 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5480 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5481 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5482 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5483 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5484 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5485 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5486 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5487 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5488 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5489 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5490 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5491 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5492 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5493 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5494 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5495 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5496 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5497 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5498 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5499 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5500 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5501 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5502 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5503 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5504 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5505 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5506 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5507 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5508 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5509 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5510 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5511 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5512 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5513 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5514 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5515 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5516 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5517 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5518 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5519 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5520 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5521 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5522 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5523 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5524 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5525 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5526 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5527 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5528 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5529 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5530 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5531 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5532 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5533 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5534 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5535 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5536 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5537 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5538 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5539 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5540 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5541 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5542 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5543 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5544 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5545 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5546 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5547 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5548 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5549 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5550 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5551 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5552 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5553 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5554 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5555 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5556 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5557 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5558 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5559 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5560 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5561 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5562 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5563 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5564 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5565 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5566 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5567 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5568 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5569 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5570 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5571 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5572 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5573 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5574 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5575 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5576 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5577 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5578 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5579 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5580 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5581 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5582 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5583 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5584 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5585 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5586 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5587 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5588 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5589 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5590 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5591 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5592 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5593 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5594 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5595 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5596 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5597 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5598 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5599 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5600 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5601 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5602 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5603 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5604 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5605 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5606 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5607 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5608 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5609 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5610 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5611 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5612 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5613 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5614 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5615 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5616 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5617 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5618 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5619 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5620 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5621 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5622 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5623 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5624 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5625 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5626 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5627 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5628 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5629 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5630 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5631 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5632 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5633 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5634 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5635 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5636 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5637 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5638 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5639 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5640 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5641 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5642 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5643 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5644 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5645 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5646 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5647 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5648 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5649 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5650 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5651 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5652 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5653 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5654 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5655 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5656 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5657 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5658 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5659 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5660 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5661 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5662 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5663 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5664 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5665 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5666 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5667 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5668 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5669 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5670 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5671 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5672 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5673 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5674 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5675 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5676 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5677 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5678 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5679 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5680 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5681 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5682 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5683 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5684 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5685 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5686 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5687 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5688 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5689 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5690 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5691 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5692 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5693 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5694 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5695 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5696 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5697 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5698 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5699 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5700 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5701 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5702 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5703 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5704 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5705 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5706 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5707 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5708 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5709 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5710 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5711 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5712 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5713 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5714 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5715 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5716 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5717 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5718 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5719 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5720 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5721 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5722 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5723 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5724 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5725 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5726 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5727 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5728 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5729 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5730 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5731 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5732 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5733 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5734 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5735 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5736 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5737 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5738 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5739 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5740 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5741 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5742 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5743 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5744 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5745 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5746 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5747 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5748 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5749 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5750 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5751 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5752 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5753 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5754 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5755 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5756 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5757 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5758 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5759 ) 
INSERT INTO [BryantDB].[dbo].[Grade] VALUES   ( NULL  ,5760 ) 