
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 1 , 1 , 6 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 2 , 2 , 7 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 3 , 3 , 8 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 4 , 1 , 9 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 5 , 2 , 10 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 6 , 3 , 11 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 7 , 1 , 12 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 8 , 2 , 13 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 9 , 3 , 14 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 10 , 1 , 15 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 11 , 2 , 16 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 12 , 3 , 17 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 1 , 1 , 18 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 2 , 2 , 19 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 3 , 3 , 20 , 1 , 1) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 4 , 1 , 21 , 2 , 2) 
INSERT INTO [BryantDB].[dbo].[coursesection] VALUES ( 5 , 2 , 22 , 1 , 1) 
