INSERT INTO [BryantDB].[dbo].[User] VALUES('riley@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Anatasia Riley')
INSERT INTO [BryantDB].[dbo].[User] VALUES('arnold@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Isabelle Arnold')
INSERT INTO [BryantDB].[dbo].[User] VALUES('kennedy@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Sharon Kennedy')
INSERT INTO [BryantDB].[dbo].[User] VALUES('briggs@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Aminah Briggs')
INSERT INTO [BryantDB].[dbo].[User] VALUES('peters@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Georgina Peters')
INSERT INTO [BryantDB].[dbo].[User] VALUES('faulkner@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Aidan Faulkner')
INSERT INTO [BryantDB].[dbo].[User] VALUES('mcfarlane@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Phoebe Mcfarlane')
INSERT INTO [BryantDB].[dbo].[User] VALUES('owens@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Willie Owens')
INSERT INTO [BryantDB].[dbo].[User] VALUES('dunn@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Rosemary Dunn')
INSERT INTO [BryantDB].[dbo].[User] VALUES('daniel@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Kaitlyn Daniel')
INSERT INTO [BryantDB].[dbo].[User] VALUES('barrett@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Kara Barrett')
INSERT INTO [BryantDB].[dbo].[User] VALUES('castillo@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Caroline Castillo')
INSERT INTO [BryantDB].[dbo].[User] VALUES('schwartz@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Aleena Schwartz')
INSERT INTO [BryantDB].[dbo].[User] VALUES('mann@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Ashley Mann')
INSERT INTO [BryantDB].[dbo].[User] VALUES('ward@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Rachael Ward')
INSERT INTO [BryantDB].[dbo].[User] VALUES('porter@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Imogen Porter')
INSERT INTO [BryantDB].[dbo].[User] VALUES('rogers@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Charlotte Rogers')
INSERT INTO [BryantDB].[dbo].[User] VALUES('zimmerman@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Alice Zimmerman')
INSERT INTO [BryantDB].[dbo].[User] VALUES('freeman@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Minnie Freeman')
INSERT INTO [BryantDB].[dbo].[User] VALUES('allen@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Gabrielle Allen')
INSERT INTO [BryantDB].[dbo].[User] VALUES('walsh@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Eva Walsh')
INSERT INTO [BryantDB].[dbo].[User] VALUES('guzman@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Leah Guzman')
INSERT INTO [BryantDB].[dbo].[User] VALUES('fox@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Annabel Fox')
INSERT INTO [BryantDB].[dbo].[User] VALUES('carson@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Aoife Carson')
INSERT INTO [BryantDB].[dbo].[User] VALUES('curry@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Ayesha Curry')
INSERT INTO [BryantDB].[dbo].[User] VALUES('howell@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Tanya Howell')
INSERT INTO [BryantDB].[dbo].[User] VALUES('barker@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Bryan Barker')
INSERT INTO [BryantDB].[dbo].[User] VALUES('morton@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Saif Morton')
INSERT INTO [BryantDB].[dbo].[User] VALUES('rhodes@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Jamal Rhodes')
INSERT INTO [BryantDB].[dbo].[User] VALUES('cole@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Wayne Cole')
INSERT INTO [BryantDB].[dbo].[User] VALUES('duran@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Malachi Duran')
INSERT INTO [BryantDB].[dbo].[User] VALUES('sims@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Jose Sims')
INSERT INTO [BryantDB].[dbo].[User] VALUES('cummings@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Leonard Cummings')
INSERT INTO [BryantDB].[dbo].[User] VALUES('mitchell@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Owen Mitchell')
INSERT INTO [BryantDB].[dbo].[User] VALUES('jimenez@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Terry Jimenez')
INSERT INTO [BryantDB].[dbo].[User] VALUES('castro@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Mohamed Castro')
INSERT INTO [BryantDB].[dbo].[User] VALUES('davidson@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Scott Davidson')
INSERT INTO [BryantDB].[dbo].[User] VALUES('day@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Ciaran Day')
INSERT INTO [BryantDB].[dbo].[User] VALUES('parsons@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Xavier Parsons')
INSERT INTO [BryantDB].[dbo].[User] VALUES('higgins@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Zachariah Higgins')
INSERT INTO [BryantDB].[dbo].[User] VALUES('armstrong@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','John Armstrong')
INSERT INTO [BryantDB].[dbo].[User] VALUES('frost@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Yusuf Frost')
INSERT INTO [BryantDB].[dbo].[User] VALUES('matthews@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Julia Matthews')
INSERT INTO [BryantDB].[dbo].[User] VALUES('houston@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Wesley Houston')
INSERT INTO [BryantDB].[dbo].[User] VALUES('gomez@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Jackson Gomez')
INSERT INTO [BryantDB].[dbo].[User] VALUES('mejia@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Morgan Mejia')
INSERT INTO [BryantDB].[dbo].[User] VALUES('gibbs@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Alex Gibbs')
INSERT INTO [BryantDB].[dbo].[User] VALUES('ward@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Maxwell Ward')
INSERT INTO [BryantDB].[dbo].[User] VALUES('stewart@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Harold Stewart')
INSERT INTO [BryantDB].[dbo].[User] VALUES('christie@mamba.edu','$2a$12$mgIW22sS2uhKTduaFNugJeym8Li6VnFlyNRDWBC7Oaf39lIaBkBOq','Dean Christie')

INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(6,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(7,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(8,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(9,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(10,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(11,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(12,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(13,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(14,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(15,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(16,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(17,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(18,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(19,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(20,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(21,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(22,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(23,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(24,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(25,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(26,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(27,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(28,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(29,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(30,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(31,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(32,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(33,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(34,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(35,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(36,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(37,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(38,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(39,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(40,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(41,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(42,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(43,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(44,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(45,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(46,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(47,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(48,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(49,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(50,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(51,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(52,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(53,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(54,2)
INSERT INTO [BryantDB].[dbo].[UserRole] VALUES(55,2)
