
--Major Pre-Requirments

--American Studies

INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,4) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10 ,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 

--Biological Sciences
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,4) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,NULL) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10 ,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (13,12) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (14,13) 

--Criminology
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,NULL) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,NULL) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10 ,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,9) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,8) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (13,12) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (14,13) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (14,12) 

--American History

INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,9) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,10) 

--Accounting
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,9) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,8) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (13,11)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (13,12) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (14,13)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (15,13) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (15,14) 

--Arabic
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,NULL) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,9) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,8) 
 INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,10) 


--Behavioral Sciences

INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,9) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,8) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (12,11) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (13,11)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (13,12) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (14,13)



--Business Administration and Management.
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,5)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)

--Anthropology

INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,5)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (11,10)


--Visual studes
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,5)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,8)


--Englsih

INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (1,NULL)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (4,3) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (6,5)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (7,6)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (8,7)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (9,8)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisite] VALUES  (10,9)

