INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (2,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (3,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (4,2) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (5,4)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (6,1)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (8,4) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (9,8) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (10 ,9)
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (11,10) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (11,9) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (11,8) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (12,4) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (13,4) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (14,4) 
INSERT INTO [BryantDB].[dbo].[MajorPreRequisites] VALUES  (14,9) 

